---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dingotiles/dingo-haproxy-pivotaltile-pipeline

inputs:
  - name: tile
  - name: tile-version
  - name: product-tile
  - name: haproxy-boshrelease
    path: haproxy
  - name: prometheus-boshrelease
    path: prometheus
  - name: pivnet-stemcell

outputs:
  - name: product

params:
  product_name:

run:
  path: tile/ci/tasks/generate-product.sh
