---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dingotiles/dingo-haproxy-pivotaltile-pipeline

inputs:
  - name: tile
  - name: pivnet-stemcell

params:
  opsmgr_url:
  opsmgr_skip_ssl_verification:
  opsmgr_username:
  opsmgr_password:

run:
  path: tile/ci/tasks/upload-stemcell.sh
